# Generated by Django 5.0.7 on 2024-07-30 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('saldoInicialCaja', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldoInicialBanco', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('saldoFinalCaja', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('saldoFinalBanco', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('ivaIngresoTotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('ivaEgresoTotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='EntradaDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('numeroComprobante', models.CharField(editable=False, max_length=10)),
                ('ingresoCaja', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('egresoCaja', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ingresoBanco', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('egresoBanco', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ivaIngreso', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('ivaEgreso', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=18)),
                ('libroDiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionLibro.librodiario')),
            ],
        ),
    ]
