# Generated by Django 5.0.6 on 2024-07-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionLibro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradadiario',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='entradadiario',
            name='egresoBanco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='entradadiario',
            name='egresoCaja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='entradadiario',
            name='ingresoBanco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='entradadiario',
            name='ingresoCaja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='entradadiario',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='entradadiario',
            name='ivaEgreso',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='entradadiario',
            name='ivaIngreso',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='entradadiario',
            name='numeroComprobante',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
