# Generated by Django 5.0.6 on 2024-07-30 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionLibro', '0002_alter_entradadiario_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradadiario',
            name='numeroComprobante',
        ),
    ]
